export const PERMISSIONS = {
  DOCUMENT_READ: "document.read",
  DOCUMENT_UPLOAD: "document.upload",
  DOCUMENT_UPDATE_OWN: "document.update_own",
  DOCUMENT_VERSION: "document.version",
  DOCUMENT_DOWNLOAD: "document.download",
  DOCUMENT_PRINT: "document.print",
  DOCUMENT_DELETE_OWN: "document.delete_own",
  MATTER_READ: "matter.read",
  MATTER_CREATE: "matter.create",
  MATTER_UPDATE_OWN: "matter.update_own",
  MATTER_DELETE_OWN: "matter.delete_own",
  MATTER_FINANCE_MANAGE: "matter.finance.manage",
  ASSET_READ: "asset.read",
  ASSET_SUBMIT: "asset.submit",
  ASSET_CREATE: "asset.create",
  ASSET_UPDATE: "asset.update",
  ASSET_IMPORT: "asset.import",
  ASSET_EXPORT: "asset.export",
  ASSET_BORROW: "asset.borrow",
  ASSET_RETURN: "asset.return",
  ASSET_RESERVE: "asset.reserve",
  ASSET_TRANSFER: "asset.transfer",
  ASSET_INVENTORY: "asset.inventory",
  ASSET_MAINTENANCE: "asset.maintenance",
  ASSET_EXIT: "asset.exit",
  ASSET_APPROVE: "asset.approve",
  APPROVAL_READ_OWN: "approval.read_own",
  APPROVAL_REVIEW: "approval.review",
  AI_USE: "ai.use",
  AI_CONFIGURE: "ai.configure",
  AUDIT_READ: "audit.read",
  SYSTEM_MANAGE: "system.manage",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS] | string;

export const LEGACY_EMPLOYEE_PERMISSIONS = new Set<PermissionCode>([
  PERMISSIONS.DOCUMENT_READ,
  PERMISSIONS.DOCUMENT_UPLOAD,
  PERMISSIONS.DOCUMENT_UPDATE_OWN,
  PERMISSIONS.DOCUMENT_VERSION,
  PERMISSIONS.DOCUMENT_DOWNLOAD,
  PERMISSIONS.DOCUMENT_PRINT,
  PERMISSIONS.DOCUMENT_DELETE_OWN,
  PERMISSIONS.MATTER_READ,
  PERMISSIONS.MATTER_CREATE,
  PERMISSIONS.MATTER_UPDATE_OWN,
  PERMISSIONS.MATTER_DELETE_OWN,
  PERMISSIONS.MATTER_FINANCE_MANAGE,
  PERMISSIONS.ASSET_READ,
  PERMISSIONS.ASSET_SUBMIT,
  PERMISSIONS.ASSET_BORROW,
  PERMISSIONS.ASSET_RETURN,
  PERMISSIONS.ASSET_RESERVE,
  PERMISSIONS.APPROVAL_READ_OWN,
  PERMISSIONS.AI_USE,
]);
